// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfmyrqzrwamygvyibdbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmbXlycXpyd2FteWd2eWliZGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MTg0NjUsImV4cCI6MjA3NTI5NDQ2NX0.ljsvNbqcCb8XUX2GT4_rE1_MaRAGKACKFUhOeYsPQN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);